### ISSUE TITLE
Generated project is missing required task files

### ISSUE THREAD

**Issue by rblopes** [the-simian/slush-phaser-webpack#7]
The package published on npm (and the repository) is missing required template files.

When trying to run the generated project, with Gulp, it fails after trying to, unsuccessfully, load the following files:
- `gulp/build/index.js`
- `gulp/build/scripts.js`

Manually copying these files from the [sample output repository](https://github.com/the-simian/phaser-webpack-output-example/) solves the issue, though, and the game builds normally.

**Comment by the-simian** [comment]
@rblopes thank you! I made an update last night and must have had a minor slip up.I'll fix that today

**Comment by the-simian** [comment]
references #2 - will still fail until this is really resolved.

**Comment by the-simian** [comment]
@rblopes rblopes Ok its fixed, It was kind of an unusual situation, apparently, the npm ignore file that was nested in the templates directory, was causing the build folder to be ignored.

Thanks for catching this, as it was working great for me (because I had the files), and wouldn't have caught it so quickly.

So I'm closing the issue. Thanks again, let me know if you encounter anything else!
